sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t abj/docker-react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=false abj/docker-react-app npm run test -- --coverage

# after_success:
#   - echo "Test success"

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-app"
  env:  "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-092890132765"
  bucket_path: "docker-react-app"
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY